clone_depth: 1

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install

build: off

test_script:
  - node --version && npm --version
  - cmd: npm test

environment:
  matrix:
    - nodejs_version: "LTS"
    - nodejs_version: "stable"

platform:
  - x86
  - x64
